package my.news.news;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBoxGroup;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AddProfileDesign extends VerticalLayout {
	protected TextField name;
	protected ComboBox<my.news.news.Sources> topic;
	protected NativeSelect<my.news.news.Sources> language;
	protected CheckBoxGroup<my.news.news.Sources> sources;
	protected Button btnAddSrc;
	protected GridLayout words;
	protected GridLayout keywords;
	protected TextField text1;
	protected TextField text2;
	protected TextField text3;
	protected Button add;
	protected HorizontalLayout buttons;
	protected Button save;
	protected Button stop;

	public AddProfileDesign() {
		Design.read(this);
	}
}
